FROM php-fpm-base

RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN apt-get update \
    && apt-get -y install unzip zlib1g-dev \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* \
    && docker-php-ext-install zip
    

RUN docker-php-ext-install pcntl
COPY ./application /application
RUN php /usr/local/bin/composer -d memory_limit=-1 install
